server:
  port: 8080
  error:
    include-message: always
local:
  property:
    host:
      #ms-bank-account: localhost
      ms-credits: localhost
      ms-loan: localhost
spring:
  application:
    name: service-client
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BankClientDB
      auto-index-creation: true
  config:
    import: optional:configserver:http://ms-config-server:8888
  cloud:
    config:
      # failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      client:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde local